package br.edu.ifpb.dac.sape.system;

//Generated by Selenium IDE
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CreateLocal {
	
	
	private WebDriver driver;

	@BeforeAll
	public void setUp() {
		System.setProperty("webdriver.chrome.driver",
				"/ssp/webDriver/chromedriver_win32/chromedriver.exe");

		driver = new ChromeDriver();
		
	}

	@AfterAll
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void criandolocal() {
		driver.get("http://localhost:3000/");
		driver.manage().window().setSize(new Dimension(1536, 824));
		driver.findElement(By.linkText("Locais")).click();
		driver.findElement(By.cssSelector(".btn-viewplace")).click();
		driver.findElement(By.id("lab")).click();
		driver.findElement(By.id("lab")).sendKeys("local aleatorio");
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > #lab")).click();
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > #lab")).sendKeys("local perto de nada");
		driver.findElement(By.id("mui-26293")).click();
		driver.findElement(By.id("mui-26293-option-0")).click();
		driver.findElement(By.cssSelector(".capacity > #lab")).click();
		driver.findElement(By.cssSelector(".capacity > #lab")).sendKeys("25");
		driver.findElement(By.id("flexCheckDefault")).click();
		driver.findElement(By.cssSelector(".btn-primary")).click();
	}
}

